# Generated by Django 4.1.4 on 2023-03-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Fitness', 'Fitness'), ('Gardening', 'Gardening'), ('Furniture', 'Furniture'), ('Decoratives', 'Decoratives'), ('Home-Appliances', 'Home-Appliances'), ('Fashion', 'Fashion'), ('Health', 'Health'), ('Other', 'Other')], default='Clothing', max_length=50),
        ),
    ]
