# Generated by Django 4.1.4 on 2023-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0003_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Fitness', 'Fitness'), ('Gardening', 'Gardening'), ('Furniture', 'Furniture'), ('Decoratives', 'Decoratives'), ('Home-Appliances', 'Home-Appliances'), ('Foot wear', 'Foot wear'), ('Health', 'Health'), ('Toys', 'Toys'), ('Other', 'Other')], default='Clothing', max_length=50),
        ),
    ]
