# Generated by Django 4.1.4 on 2023-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0004_alter_product_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='product_pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='product_delivery',
            field=models.CharField(choices=[('Free delivery', 'Free delivery'), ('Paid delivery', 'Paid delivery')], default='Free delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='static'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
