# Generated by Django 4.1.4 on 2023-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0005_rename_desc_product_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
