# Generated by Django 4.1.4 on 2023-05-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0010_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='categroy_image',
            new_name='category_image',
        ),
    ]
