# Generated by Django 4.1.4 on 2023-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0011_rename_categroy_image_productcategory_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Fitness', 'Fitness'), ('Gardening', 'Gardening'), ('Furniture', 'Furniture'), ('Decoratives', 'Decoratives'), ('Home-Appliances', 'Home-Appliances'), ('Foot wear', 'Foot wear'), ('Health', 'Health'), ('Toys', 'Toys'), ('Other', 'Other')], default='Clothing', max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(default='', upload_to='images')),
                ('product_desc', models.CharField(max_length=500)),
                ('product_pub_date', models.DateField()),
                ('product_price', models.IntegerField(default=0)),
                ('product_delivery', models.CharField(choices=[('Free delivery', 'Free delivery'), ('Paid delivery', 'Paid delivery')], default='Free delivery', max_length=50)),
                ('product_delivery_price', models.IntegerField(default=0)),
            ],
        ),
    ]
