# Generated by Django 4.1.4 on 2023-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0012_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
