# Generated by Django 4.1.4 on 2023-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0013_usercart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product_id',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
