# Generated by Django 4.1.4 on 2023-05-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0014_alter_usercart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product_id',
        ),
    ]
