# Generated by Django 4.1.4 on 2023-05-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0015_remove_usercart_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='', max_length=1000)),
                ('is_user_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
