# Generated by Django 4.2.2 on 2023-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0016_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='is_user_verified',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
