# Generated by Django 4.2.2 on 2023-06-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0017_remove_userlogin_is_user_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1000)),
                ('user_gender', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(default='', max_length=1000)),
                ('user_mob', models.CharField(default='', max_length=10)),
                ('user_add', models.CharField(default='', max_length=1000)),
                ('pan_no', models.CharField(default='', max_length=10)),
                ('pan_img', models.ImageField(default='', upload_to='userPancardImg')),
                ('payment_method', models.CharField(default='c_o_d', max_length=1000)),
            ],
        ),
    ]
