# Generated by Django 4.1.4 on 2023-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0018_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=500)),
                ('product_gross_price', models.IntegerField(default=0, max_length=100000)),
                ('product_delivered_address', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_mob',
            field=models.CharField(default='', max_length=12),
        ),
    ]
