# Generated by Django 4.1.4 on 2023-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0019_userorders_alter_userprofile_user_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='product_gross_price',
            field=models.IntegerField(default=0),
        ),
    ]
