# Generated by Django 4.1.4 on 2023-07-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0020_alter_userorders_product_gross_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrders',
            new_name='UserOrder',
        ),
    ]
