# Generated by Django 4.1.4 on 2023-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0021_rename_userorders_userorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='product',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='userorder',
            name='product_img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
