# Generated by Django 4.1.4 on 2023-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0023_userorder_is_order_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
