# Generated by Django 4.1.4 on 2023-08-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0024_usercart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
