# Generated by Django 4.1.4 on 2024-03-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0025_userorder_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product_id',
        ),
    ]
