# Generated by Django 4.1.4 on 2024-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0027_sellerlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlogin',
            name='seller_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
