# Generated by Django 4.1.4 on 2024-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0028_alter_sellerlogin_seller_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(default='', max_length=1000)),
                ('seller_email', models.EmailField(max_length=1000)),
                ('seller_mob', models.CharField(default='', max_length=11)),
                ('home_add', models.CharField(default='', max_length=1000)),
                ('business_name', models.CharField(default='', max_length=1000)),
                ('business_regis_no', models.CharField(default='', max_length=1000)),
                ('gst_no', models.CharField(default='', max_length=100)),
                ('business_add', models.CharField(default='', max_length=1000)),
                ('bank_name', models.CharField(default='', max_length=1000)),
                ('account_no', models.CharField(default='', max_length=100)),
                ('ship_mode', models.CharField(default='', max_length=1000)),
                ('ship_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
