# Generated by Django 4.1.4 on 2024-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0029_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.IntegerField(default=0),
        ),
    ]
