# Generated by Django 4.1.4 on 2024-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0030_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_id',
            field=models.IntegerField(default=0),
        ),
    ]
