# Generated by Django 4.1.4 on 2024-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0032_product_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(default=3),
        ),
    ]
