# Generated by Django 4.1.4 on 2024-05-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0033_alter_product_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_purchases',
            field=models.IntegerField(default=0),
        ),
    ]
