# Generated by Django 4.1.4 on 2024-05-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0034_product_product_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_purchases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercart',
            name='product_rating',
            field=models.IntegerField(default=3),
        ),
    ]
