# Generated by Django 4.1.4 on 2024-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0035_usercart_product_purchases_usercart_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(max_length=3000),
        ),
    ]
